// <auto-generated />
using System;
using IForgor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IForgor.Infrastructure.Migrations
{
    [DbContext(typeof(IforgorDbContext))]
    [Migration("20240521145830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IForgor.Domain.DeskAggregate.Desk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Desks", (string)null);
                });

            modelBuilder.Entity("IForgor.Domain.DeskAggregate.Desk", b =>
                {
                    b.OwnsMany("IForgor.Domain.FieldAggregate.ValueObjects.FieldId", "FieldIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("DeskId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("FieldId");

                            b1.HasKey("Id");

                            b1.HasIndex("DeskId");

                            b1.ToTable("DeskFieldIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeskId");
                        });

                    b.OwnsMany("IForgor.Domain.ProjectAggregate.ValueObjects.ProjectId", "ProjectIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("DeskId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ProjectId");

                            b1.HasKey("Id");

                            b1.HasIndex("DeskId");

                            b1.ToTable("DeskProjectIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeskId");
                        });

                    b.OwnsMany("IForgor.Domain.StudySubjectAggregate.ValueObjects.StudySubjectId", "StudySubjectIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("DeskId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("StudySubjectId");

                            b1.HasKey("Id");

                            b1.HasIndex("DeskId");

                            b1.ToTable("DeskStudySubjectsIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeskId");
                        });

                    b.Navigation("FieldIds");

                    b.Navigation("ProjectIds");

                    b.Navigation("StudySubjectIds");
                });
#pragma warning restore 612, 618
        }
    }
}
